name: 'setup-docker-action'
description: 'Setup docker and docker buildx'
inputs:
  docker-username:
    description: "username for docker registry"
    required: true
  docker-password:
    description: "password for docker registry"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}
