
#define PACKAGE_NAME ""
#define PACKAGE_TARNAME ""
#define PACKAGE_VERSION ""
#define PACKAGE_STRING ""
#define PACKAGE_BUGREPORT ""
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_DLFCN_H 1
#ifdef __cplusplus
extern "C" void std::exit (int) throw (); using std::exit;
#endif
#define HAVE_RAND_STATUS 1
#define HAVE_SSL 1
#define STDC_HEADERS 1
#define HAVE_SYS_WAIT_H 1
#define TIME_WITH_SYS_TIME 1
#define HAVE_DIRENT_H 1
#define HAVE_LINUX_MSG_H 1
#define HAVE_SYS_MSG_H 1
#define HAVE_SYS_IPC_H 1
#define HAVE_UNISTD_H 1
#define HAVE_GETOPT_H 1
#define HAVE_STRING_H 1
#define HAVE_STRINGS_H 1
#define HAVE_SYS_UIO_H 1
#define HAVE_SYS_PARAM_H 1
#define HAVE_NETINET_IN_SYSTM_H 1
#define HAVE_NETINET_IN_H 1
#define HAVE_NETINET_IN_SYSTM_H 1
#define HAVE_NETINET_IP_H 1
#define HAVE_NETINET_IP_ICMP_H 1
#define HAVE_NETINET_IP_H 1
#define HAVE_SYS_SOCKET_H 1
#define HAVE_SYS_RESOURCE_H 1
#define HAVE_NET_IF_H 1
#define HAVE_SYS_IOCTL_H 1
#define HAVE_RPC_RPC_H 1
#define HAVE_DLFCN_H 1
#define HAVE_SYS_UN_H 1
#define HAVE_MEMORY_H 1
#define HAVE_CTYPE_H 1
#define HAVE_ERRNO_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STDIO_H 1
#define HAVE_PTHREAD_H 1
#define HAVE_PWD_H 1
#define HAVE_ASSERT_H 1
#define HAVE_NETDB_H 1
#define HAVE_ARPA_INET_H 1
#define HAVE_SETJMP_H 1
#define HAVE_POLL_H 1
#define HAVE_SYS_POLL_H 1
#define HAVE_FCNTL_H 1
#define HAVE_SIGNAL_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_MMAN_H 1
#define HAVE_TERMIO_H 1
#define HAVE_TERMIOS_H 1
#define HAVE_SGTTY_H 1
#define HAVE_STROPTS_H 1
#define HAVE_VALUES_H 1
#define HAVE_SYS_PARAM_H 1
#define HAVE_SYS_SYSCTL_H 1
#define HAVE_LIMITS_H 1
#define HAVE_ALLOCA_H 1
#define HAVE_ALLOCA 1
#define HAVE_SIGACTION 1
#define HAVE_SYSCTL 1
#define HAVE_SETITIMER 1
#define HAVE_LSTAT 1
#define HAVE_MEMMOVE 1
#define HAVE_GETTIMEOFDAY 1
#define HAVE_GETRUSAGE 1
#define HAVE_RAND 1
#define HAVE_STRCHR 1
#define HAVE_MEMCPY 1
#define HAVE_SELECT 1
#define HAVE_POLL 1
#define HAVE_UNLOCKPT 1
#define HAVE_VSNPRINTF 1
#define HAVE_SNPRINTF 1
#define HAVE_VASPRINTF 1
#define HAVE_ASPRINTF 1
#define HAVE_BZERO 1
#define HAVE_BCOPY 1
#define HAVE_SETSID 1
#define HAVE_INET_NETA 1
#define HAVE_LRAND48 1
#define HAVE_SETITIMER 1
#define HAVE_SENDMSG 1
#define HAVE_RECVMSG 1
#define HAVE_GETOPT_LONG 1
#define HAVE_OPENPTY 1
#define HAVE_DEV_PTMX 1
#define HAVE_GRANTPT 1
#define HAVE_PTSNAME 1
#define HAVE_INET_ATON 1
#define HAVE_INET_ATON 1
#define HAVE_INET_ATON 1
#define HAVE_STRUCT_IFMAP 1
#define HAVE_TIMEVAL 1
#define HAVE_OPTIND 1
#define HAVE_CONTROL_IN_MSGHDR 1
#define HAVE_LONG_FILE_NAMES 1
#define LINUX 1
