.TH NESSUS-CONFIG 1 "November 1999" "Debian Project" "Nessus"
.SH NAME
nessus-config \- displays compiler/linker flags for the Nessus libraries
.SH SYNOPSIS
.B nessus-config
.I <[--cflags] [--ldflags] [--libs]>
.SH DESCRIPTION
.BR nessus-config
script displays the compiler/linker flags other program sources
can use to link to the Nessus libraries.
.SH OPTIONS
.TP
.B \-\-cflags
Show $(CFLAGS) variable.
.TP
.B \-\-libs
Show $(LIBS) variable.
.TP
.B \-\-version
Show the version of the Nessus libraries.
.SH SEE ALSO
.BR nessus (1),
.BR nessusd (8).
.SH AUTHOR
Nessus is made by Renaud Deraison <deraison@cvs.nessus.org>.
.sp
This manual page was written by Josip Rodin <jrodin@jagor.srce.hr>.
