name: 'determine-tags-action'
description: 'Determine version and latest tags'
runs:
  using: "composite"
  steps:
    - name: "set IS_VERSION_TAG"
      run: |
        echo "IS_VERSION_TAG=${{ github.ref_type == 'tag' && startsWith(github.ref_name, 'v') }}" >> $GITHUB_ENV
        # set defaults
        echo "IS_LATEST_TAG=false" >> $GITHUB_ENV
    - name: "set IS_LATEST_TAG"
      if: ( env.IS_VERSION_TAG )
      run: |
        # find the latest version that is not ourself
        export LATEST_VERSION=$(git tag -l | grep -v '${{ github.ref_name }}' | sort -r --version-sort)
        # get major minor patch versions
        IFS='.' read -r latest_major latest_minor latest_patch << EOF
        $LATEST_VERSION
        EOF
        IFS='.' read -r tag_major tag_minor tag_patch << EOF
        ${{ github.ref_name }}
        EOF
        # remove leading v
        latest_major=$(echo $latest_major | cut -c2-)
        tag_major=$(echo $tag_major | cut -c2-)
        echo "$tag_major >= $latest_major"
        if [[ $tag_major -ge $latest_major && ($tag_minor -ne 0 || $tag_patch -ne 0) ]]; then
          # set this tag to latest and stable
          echo "IS_LATEST_TAG=true" >> $GITHUB_ENV
        fi
