.TH LIBOPENVAS-CONFIG 1 "November 1999" "Debian Project" "OpenVAS"
.SH NAME
libopenvas-config \- displays compiler/linker flags for the OpenVAS libraries
.SH SYNOPSIS
.B libopenvas-config
.I <[--cflags] [--ldflags] [--libs]>
.SH DESCRIPTION
.BR libopenvas-config
script displays the compiler/linker flags other program sources
can use to link to the OpenVAS libraries.
.SH OPTIONS
.TP
.B \-\-cflags
Show $(CFLAGS) variable.
.TP
.B \-\-libs
Show $(LIBS) variable.
.TP
.B \-\-version
Show the version of the OpenVAS libraries.
.SH SEE ALSO
.BR openvasd (8).
.SH AUTHOR
Renaud Deraison <deraison@cvs.nessus.org>.
.sp
This manual page was written by Josip Rodin <jrodin@jagor.srce.hr>.
