macro (add_unit_test _testName _testSource)
  add_executable(${_testName} ${_testSource})
  target_link_libraries(${_testName} ${CGREEN_LIBRARIES} ${ARGN})
  target_include_directories(${_testName} PRIVATE ${CGREEN_INCLUDE_DIRS})
  add_test(NAME ${_testName} COMMAND ${CMAKE_CURRENT_BINARY_DIR}/${_testName})
endmacro ()
