name: "[Scheduled] Build and upload docker images"
on:
  schedule:
    - cron: '0 */3 * * *' # every 2h

jobs:
  upload-testing:
    name: "Upload testing docker images"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler:
          - gcc
          - clang
        branches: [ master, gvm-libs-20.08, gvm-libs-21.04, middleware ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{matrix.branches}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        # this only works with github.ref on push not on pull_request. ;)
      - run: echo "Build and push ${{ github.repository }}-${{matrix.branches}}-${{matrix.compiler}}-testing"
      - name: Build and push
        uses: docker/build-push-action@v2.5.0
        with:
          context: .
          push: true
          tags: ${{ github.repository }}-${{matrix.branches}}-${{matrix.compiler}}-testing
          file: .docker/testing/Dockerfile
          build-args: |
            VERSION=${{matrix.branches}}
            COMPILER=${{matrix.compiler}}
  upload-build:
    needs: upload-testing
    name: "Upload build docker images"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler:
          - gcc
          - clang
        branches: [ master, gvm-libs-20.08, gvm-libs-21.04, middleware ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{matrix.branches}}
      - name: Find version
        run: |
          if [ ${{matrix.branches}} = "master" ];                                 \
          then VERSION=master;                                       \
          else VERSION=$(echo "${{matrix.branches}} " | sed 's/gvm-libs-//g' -);       \
          fi;
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        # this only works with github.ref on push not on pull_request. ;)
      - run: echo "Build and push ${{ github.repository }}-${{ env.VERSION }}-${{matrix.compiler}}-build"
      - name: Build and push
        uses: docker/build-push-action@v2.5.0
        with:
          context: .
          push: true
          tags: ${{ github.repository }}-${{ env.VERSION }}-${{matrix.compiler}}-build
          file: .docker/build/Dockerfile
          build-args: |
            VERSION=${{ env.VERSION }}
            COMPILER=${{matrix.compiler}}
